name: Build and Deploy Documentation
on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: Get Material Theme
        uses: GuillaumeFalourd/clone-github-repo-action@v1
        with:
          owner: ovasquez
          repository: docfx-material

      - name: Copy Theme Files
        run: |
          cp -R docfx-material/material docs/templates

      - name: Build Docs
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: docs/docfx.json

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: site/html

